---
- hosts: all
    name: deploy packages
    vars:

    tasks:
      - name: install basic packages
        become: yes
        become_method: sudo
        yum: pkg={{item}} state=installed
        with_items:
          - openldap
          - compat-openldap
          - openldap-clients
          - openldap-servers
          - openldap-servers-sql
          - openldap-devel  

      - name: start service
        become: yes
        become_method: sudo
        command: systemctl start slapd.service

      - name: enable service
        become: yes
        become_method: suod
        command: systemclt enable slapd.service 
       
      - name: install net-tools
        become: yes
        become_method: sudo
        yum: pkg=net-tools state=installed

      - name: ensure slapd and port 389 is up
        become: yes
        become_method: sudo
        command: netstat -antup | grep -i 389
        register: command_output
      - debug: msg="{{command_output.stdout}}"

      - name: base ldif db
        become: yes
        become_method: sudo
        blockinfile:
          path: /tmp/db.ldif 
          block: |
            "dn: olcDatabase={2}hdb,cn=config
     	     changetype: modify
             replace: olcSuffix
             olcSuffix: dc=hdp,dc=local

             dn: olcDatabase={2}hdb,cn=config
             changetype: modify
             replace: olcRootDN
             olcRootDN: cn=ldapadm,dc=hdp,dc=local

             dn: olcDatabase={2}hdb,cn=config
             changetype: modify
             replace: olcRootPW
             olcRootPW: {SSHA}QF+jBFJ/RWGVwPuDzQI87YJfJtKOYGhK"

      - name: push ldif values
        become: yes
        become_method: sudo
        command: ldapmodify -Y external -H ldapi:/// -f /tmp/db.ldif
        resgister: command_output
      - debug: msg="{{command_output.stdout}}"
     
      - name: base monitor ldif
        become: yes
        become_method: sudo
        blockinfile:
          path: /tmp/monitor.ldif
          block: |
            "dn: olcDatabase={1}monitor,cn=config
             changetype: modify
             replace: olcAccess
             olcAccess: {0}to * by dn.base='gidNumber=0+uidNumber=0,cn=peercred,cn=external, cn=auth" read by dn.base="cn=ldapadm,dc=hdp,dc=local' read by * none"

      - name: push ldif values
        become: yes
        become_method: sudo
        command: ldapmodify -Y external -H ldapi:/// -f /tmp/monitor.ldif
        resgister: command_output
      - debug: msg="{{command_output.stdout}}"

   
