---
- hosts: all
    name: deploy packages
    vars:

    tasks:
      - name: install basic packages
        become: yes
        become_method: sudo
        yum: pkg={{item}} state=installed
        with_items:
          - openldap
          - compat-openldap
          - openldap-clients
          - openldap-servers
          - openldap-servers-sql
          - openldap-devel  

      - name: start service
        become: yes
        become_method: sudo
        command: systemctl start slapd.service

      - name: enable service
        become: yes
        become_method: suod
        command: systemclt enable slapd.service 
       
      - name: install net-tools
        become: yes
        become_method: sudo
        yum: pkg=net-tools state=installed

      - name: ensure slapd and port 389 is up
        become: yes
        become_method: sudo
        command: netstat -antup | grep -i 389
        register: command_output
      - debug: msg="{{command_output.stdout}}"

      - 

