---
- hosts: all
    name: deploy packages
    vars:

    tasks:
      - name: install basic packages
        become: yes
        become_method: sudo
        yum: pkg={{item}} state=installed
        with_items:
          - openldap
          - compat-openldap
          - openldap-clients
          - openldap-servers
          - openldap-servers-sql
          - openldap-devel  

      - name: start service
        become: yes
        become_method: sudo
        command: systemctl start slapd.service

      - name: enable service
        become: yes
        become_method: suod
        command: systemclt enable slapd.service 
       
      - name: install net-tools
        become: yes
        become_method: sudo
        yum: pkg=net-tools state=installed

      - name: ensure slapd and port 389 is up
        become: yes
        become_method: sudo
        command: netstat -antup | grep -i 389
        register: command_output
      - debug: msg="{{command_output.stdout}}"

      - name: base ldif db
        become: yes
        become_method: sudo
        blockinfile:
          path: /tmp/db.ldif 
          block: |
            "dn: olcDatabase={2}hdb,cn=config
     	     changetype: modify
             replace: olcSuffix
             olcSuffix: dc=hdp,dc=local

             dn: olcDatabase={2}hdb,cn=config
             changetype: modify
             replace: olcRootDN
             olcRootDN: cn=ldapadm,dc=hdp,dc=local

             dn: olcDatabase={2}hdb,cn=config
             changetype: modify
             replace: olcRootPW
             olcRootPW: {SSHA}QF+jBFJ/RWGVwPuDzQI87YJfJtKOYGhK"

      - name: push ldif values
        become: yes
        become_method: sudo
        command: ldapmodify -Y external -H ldapi:/// -f /tmp/db.ldif
        resgister: command_output
      - debug: msg="{{command_output.stdout}}"
     
      - name: base monitor ldif
        become: yes
        become_method: sudo
        blockinfile:
          path: /tmp/monitor.ldif
          block: |
            "dn: olcDatabase={1}monitor,cn=config
             changetype: modify
             replace: olcAccess
             olcAccess: {0}to * by dn.base='gidNumber=0+uidNumber=0,cn=peercred,cn=external, cn=auth" read by dn.base="cn=ldapadm,dc=hdp,dc=local' read by * none"

      - name: push ldif values
        become: yes
        become_method: sudo
        command: ldapmodify -Y external -H ldapi:/// -f /tmp/monitor.ldif
        resgister: command_output
      - debug: msg="{{command_output.stdout}}"

#      - name: create certificate       
      - name: change owner and group permissions
        become: yes
        become_method: sudo
        command: chown -R ldap:ldap /etc/openldap/certs/*.pem

      - name: create certs ldif
        become: yes
        become_method: sudo
        blockinfile:
          path: /tmp/certs.ldif
          block: |
            "dn: cn=config
             changetype: modify
             replace: olcTLSCertificateFile
             olcTLSCertificateFile: /etc/openldap/certs/hdpldapcert.pem

             dn: cn=config
             changetype: modify
             replace: olcTLSCertificateKeyFile
             olcTLSCertificateKeyFile: /etc/openldap/certs/hdpldapkey.pem"

      - name: push ldif values
        become: yes
        become_method: sudo
        command: ldapmodify -Y external -H ldapi:/// -f /tmp/certs.ldif
        resgister: command_output
      - debug: msg="{{command_output.stdout}}"
 
      - name: test and verify configurations
        become: yes
        become_method: sudo
        command: slaptest -u
        resgister: command_output
      - debug: msg="{{command_output.stdout}}"
        
      - name: copy template
        become: yes
        become_method: sudo
        command: cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG

      - name: change ownership
        become: yes
        become_method: sudo
        command: chown ldap:ldap /var/lib/ldap/*

      - name: add schema1
        become: yes
        become_method: sudo
        command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
      
      - name: add schema2
        become: yes
        become_method: sudo
        command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif

      - name: add schema3
        become: yes
        become_method: sudo
        command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

      - name: generate base.ldif for domain
        become: yes
        become_method: sudo
        blockinfile:
          path: /tmp/base.ldif
          block: |
            "dn: dc=hdp,dc=local
             dc: hdp 
             objectClass: top
             objectClass: domain

             dn: cn=ldapadm ,dc=hdp,dc=local
             objectClass: organizationalRole
             cn: ldapadm
             description: LDAP Manager

             dn: ou=People,dc=hdp,dc=local
             objectClass: organizationalUnit
             ou: People

             dn: ou=Group,dc=hdp,dc=local
             objectClass: organizationalUnit
             ou: Group"

      - name: build directory structure
        become: yes
        become_method: sudo
        command: ldapadd -x -W -D "cn=ldapadm,dc=hdp,dc=local" -f base.ldif
